import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import LottieAnimation from "@/components/Lottie";
import localFont from "next/font/local";
const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const revalidate = 0;
export const cache = "no-store"

const VAGRounded = localFont({
	src: [
		{
			path: "./fonts/VAGRoundedStd-Thin.otf",
			weight: "100",
		},
		{
			path: "./fonts/VAGRoundedStd-Light.otf",
			weight: "300",
		},
		{
			path: "./fonts/VAGRoundedStd-Black.otf",
			weight: "900",
		},
		{
			path: "./fonts/VAGRoundedStd-Bold.otf",
			weight: "700",
		},
	],
});

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} ${VAGRounded.className}`}>
				<header className="sticky top-[0px] w-full flex z-10 backdrop-blur-sm">
					<div className="w-full">
						<Image src="/assets/imgs/HorizontalTag.png" alt="logo" width={128} height={128} className="ml-2 mt-4" />
					</div>
					<div className="relative w-full flex flex-col">
						<div className="m-4 mt-7 size-[32px] border self-end"></div>
						<Image src="/assets/imgs/Asset 3.png" alt="" width={74} height={74} className="absolute right-0 bottom-0 translate-y-full mr-2"></Image>
					</div>
					<LottieAnimation />
				</header>
				{children}
				<footer className="h-[220px] flex content-between pb-4 pt-6 px-8 bg-[rgb(180_118_175)] text-[#fece00]">
					<div className="w-full flex flex-col">
						<div className="flex flex-col gap-[5px] text-[14px] leading-none">
							<Link href={""}>home</Link>
							<Link href={""}>shop</Link>
							<Link href={""}>members</Link>
							<Link href={""}>contact</Link>
							<Link href={""}>affiliate</Link>
						</div>
						<div className="flex mt-12 gap-2">
							<div className="size-[24px] bg-[url(/assets/imgs/social/fb.png)] bg-cover bg-no-repeat"></div>
							<div className="size-[24px] bg-[url(/assets/imgs/social/ig.png)] bg-cover bg-no-repeat"></div>
							<div className="size-[24px] bg-[url(/assets/imgs/social/tt.png)] bg-cover bg-no-repeat"></div>
						</div>
					</div>
					<div className="w-full flex flex-col-reverse items-end">
						<span className="text-[12px]">©copyright 2023 varisha</span>
						<Image className="mb-4" src={"/assets/imgs/footer-logo.webp"} alt="Footer Image" width={60} height={60}></Image>
					</div>
				</footer>
			</body>
		</html>
	);
}
